/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2025 transsion Inc.
 */

#include <math.h>
#include <stdio.h>

/*
 * The following program is used to generate the constants for
 * computing sched averages.
 *
 * Usage
 * gcc trans_gen_inv.c -o gen_inv -lm; ./gen_inv
 */

void calc_time2weight(void)
{
    long long frame_rate;
    long long x;

    printf("\n\n");

    frame_rate = 60;
    x = ((((1UL<<32))*1024*3)*frame_rate)/(1000*1000*1000*2);
    printf("#define TIME2WEIGHT_%lldFPS 0x%08llx\n", frame_rate, x);

    frame_rate = 90;
    x = ((((1UL<<32))*1024*3)*frame_rate)/(1000*1000*1000*2);
    printf("#define TIME2WEIGHT_%lldFPS 0x%08llx\n", frame_rate, x);

    frame_rate = 120;
    x = ((((1UL<<32))*1024*3)*frame_rate)/(1000*1000*1000*2);
    printf("#define TIME2WEIGHT_%lldFPS 0x%08llx\n", frame_rate, x);

    printf("\n\n");
}

#define HALFLIFE 64
#define SHIFT 32

double y;

void calc_runnable_avg_yN_inv(void)
{
    int i;
    unsigned int x;

    /* To silence -Wunused-but-set-variable warnings. */
    printf("static const u32 load_yN_inv[] = {");

    for (i = 0; i < HALFLIFE; i++) {
        x = ((1UL<<32)-1)*pow(y, i);

        if (i % 6 == 0) printf("\n\t");
        printf("0x%8x, ", x);
    }
    printf("\n};\n\n");
}

int n = -1;

/* first period */
long max = 1024;

void calc_converged_max(void)
{
    long last = 0, y_inv = ((1UL<<32)-1)*y;

    for (; ; n++) {
        if (n > -1)
            max = ((max*y_inv)>>SHIFT) + 1024;
            /*
             * This is the same as:
             * max = max*y + 1024;
             */

        if (last == max)
            break;

        last = max;
    }

    n--;
    printf("/*\n");
    printf(" * HALFLIFE=%d\n", HALFLIFE);
    printf(" * Reaches the maximum value after completing %d full periods.\n", n);
    printf(" * Decays to zero after completing %d full periods.\n", HALFLIFE*64);
    printf(" */\n");

    printf("#define LOAD_AVG_PERIOD     %d\n", HALFLIFE);
    printf("#define LOAD_AVG_MAX        %ld\n", max);
}

void main(void)
{
    y = pow(0.5, 1/(double)HALFLIFE);

    printf("/*\n");
    printf(" * WARNING: DO NOT MODIFY !!!\n");
    printf(" *\n");
    printf(" * The following macros and variables are generated by\n");
    printf(" * uas/performance/kernel_module/src/trans_gen_inv.c\n");
    printf(" *\n");
    printf(" * y ~= %.20f\n", y);
    printf(" */\n");

    //calc_time2weight();
    calc_runnable_avg_yN_inv();
    calc_converged_max();

    printf("\n");
    printf("/*\n");
    printf(" * WARNING: DO NOT MODIFY !!!\n");
    printf(" *\n");
    printf(" * The above macros and variables are generated by\n");
    printf(" * uas/performance/kernel_module/src/trans_gen_inv.c\n");
    printf(" */\n");
}

