/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2025 transsion Inc.
 */
#include <linux/version.h>
#include <trace/events/sched.h>
#include <linux/sched/clock.h>
#include <trace/hooks/sched.h>

#include "sched_common.h"
#include "trans_loading.h"
#include "trans_trace.h"

//#define TRANS_LOADING_DEBUG

/*
 * When enabled, the parameters will be the same as those used in PELT.
 */
#define ENABLE_PELT_COMPAT

/*
 * Defines the granularity for load updates, measured in microseconds (us).
 * Smaller values result in more frequent updates.
 */
#define UPDATE_GRAN_US              10

/*
 * WARNING:
 * Allowed values for HALF_LIFE are 32, 64, or 128 only.
 */
#define HALF_LIFE                   32

/*
 * Defines the minimum period for load tracking, measured in microseconds (us).
 * A period is 1024us (~1ms), representing the smallest interval at which load
 * tracking updates are recorded or processed.
 *
 * WARNING: Do not modify this value unless you are absolutely sure of what
 * you are doing, as it may impact system performance or functionality.
 */
#define LOADTRACK_PERIOD_US         (1024)

/*
 * WARNING: DO NOT MODIFY !!!
 *
 * The following macros and variables are generated by
 * uas/performance/kernel_module/src/gen_inv.c
 */

#if HALF_LIFE == 128

/*
 * y ~= 0.99459942348363317155
 */

static const u32 load_yN_inv[] = {
    0xffffffff, 0xfe9e115b, 0xfd3e0c0b, 0xfbdfed6b, 0xfa83b2da, 0xf92959ba,
    0xf7d0df72, 0xf67a416b, 0xf5257d14, 0xf3d28fdd, 0xf281773b, 0xf13230a6,
    0xefe4b99a, 0xee990f97, 0xed4f301d, 0xec0718b5, 0xeac0c6e6, 0xe97c383f,
    0xe8396a4f, 0xe6f85aaa, 0xe5b906e6, 0xe47b6c9f, 0xe33f8971, 0xe2055aff,
    0xe0ccdeeb, 0xdf9612dd, 0xde60f481, 0xdd2d8184, 0xdbfbb796, 0xdacb946e,
    0xd99d15c1, 0xd870394b, 0xd744fcc9, 0xd61b5dfd, 0xd4f35aaa, 0xd3ccf098,
    0xd2a81d91, 0xd184df61, 0xd06333da, 0xcf4318ce, 0xce248c14, 0xcd078b85,
    0xcbec14fe, 0xcad2265d, 0xc9b9bd85, 0xc8a2d85b, 0xc78d74c7, 0xc67990b4,
    0xc5672a10, 0xc4563ecb, 0xc346ccd9, 0xc238d230, 0xc12c4cc9, 0xc0213aa1,
    0xbf1799b5, 0xbe0f6808, 0xbd08a39e, 0xbc034a7e, 0xbaff5ab1, 0xb9fcd244,
    0xb8fbaf46, 0xb7fbefc9, 0xb6fd91e2, 0xb60093a7, 0xb504f333, 0xb40aaea1,
    0xb311c411, 0xb21a31a5, 0xb123f581, 0xb02f0dcb, 0xaf3b78ac, 0xae493452,
    0xad583ee9, 0xac6896a4, 0xab7a39b4, 0xaa8d2652, 0xa9a15ab4, 0xa8b6d515,
    0xa7cd93b4, 0xa6e594cf, 0xa5fed6a9, 0xa5195786, 0xa43515ad, 0xa3520f68,
    0xa2704302, 0xa18faec9, 0xa0b0510f, 0x9fd22824, 0x9ef5325f, 0x9e196e17,
    0x9d3ed9a6, 0x9c657367, 0x9b8d39b9, 0x9ab62afb, 0x99e04592, 0x990b87e1,
    0x9837f050, 0x97657d49, 0x96942d36, 0x95c3fe86, 0x94f4efa8, 0x9426ff0f,
    0x935a2b2e, 0x928e727d, 0x91c3d373, 0x90fa4c8b, 0x9031dc42, 0x8f6a8117,
    0x8ea4398a, 0x8ddf041f, 0x8d1adf5a, 0x8c57c9c3, 0x8b95c1e3, 0x8ad4c644,
    0x8a14d574, 0x8955ee02, 0x88980e80, 0x87db357f, 0x871f6196, 0x8664915b,
    0x85aac367, 0x84f1f655, 0x843a28c3, 0x8383594e, 0x82cd8698, 0x8218af42,
    0x8164d1f3, 0x80b1ed4f,
};

/*
 * HALFLIFE=128
 * Reaches the maximum value after completing 1385 full periods.
 * Decays to zero after completing 8192 full periods.
 */
#define LOAD_AVG_PERIOD     128
#define LOAD_AVG_MAX        189425
#define LOAD_AVG_INIT       126300


#elif HALF_LIFE == 64

/*
 * y ~= 0.98922801319397546393
 */

static const u32 load_yN_inv[] = {
    0xffffffff, 0xfd3e0c0b, 0xfa83b2da, 0xf7d0df72, 0xf5257d14, 0xf281773b,
    0xefe4b99a, 0xed4f301d, 0xeac0c6e6, 0xe8396a4f, 0xe5b906e6, 0xe33f8971,
    0xe0ccdeeb, 0xde60f481, 0xdbfbb796, 0xd99d15c1, 0xd744fcc9, 0xd4f35aaa,
    0xd2a81d91, 0xd06333da, 0xce248c14, 0xcbec14fe, 0xc9b9bd85, 0xc78d74c7,
    0xc5672a10, 0xc346ccd9, 0xc12c4cc9, 0xbf1799b5, 0xbd08a39e, 0xbaff5ab1,
    0xb8fbaf46, 0xb6fd91e2, 0xb504f333, 0xb311c411, 0xb123f581, 0xaf3b78ac,
    0xad583ee9, 0xab7a39b4, 0xa9a15ab4, 0xa7cd93b4, 0xa5fed6a9, 0xa43515ad,
    0xa2704302, 0xa0b0510f, 0x9ef5325f, 0x9d3ed9a6, 0x9b8d39b9, 0x99e04592,
    0x9837f050, 0x96942d36, 0x94f4efa8, 0x935a2b2e, 0x91c3d373, 0x9031dc42,
    0x8ea4398a, 0x8d1adf5a, 0x8b95c1e3, 0x8a14d574, 0x88980e80, 0x871f6196,
    0x85aac367, 0x843a28c3, 0x82cd8698, 0x8164d1f3,
};

/*
 * HALFLIFE=64
 * Reaches the maximum value after completing 692 full periods.
 * Decays to zero after completing 4096 full periods.
 */
#define LOAD_AVG_PERIOD     64
#define LOAD_AVG_MAX        94969
#define LOAD_AVG_INIT       63400


#elif HALF_LIFE == 32

/*
 * y ~= 0.97857206208770008971
 */

static const u32 load_yN_inv[] = {
    0xffffffff, 0xfa83b2da, 0xf5257d14, 0xefe4b99a, 0xeac0c6e6, 0xe5b906e6,
    0xe0ccdeeb, 0xdbfbb796, 0xd744fcc9, 0xd2a81d91, 0xce248c14, 0xc9b9bd85,
    0xc5672a10, 0xc12c4cc9, 0xbd08a39e, 0xb8fbaf46, 0xb504f333, 0xb123f581,
    0xad583ee9, 0xa9a15ab4, 0xa5fed6a9, 0xa2704302, 0x9ef5325f, 0x9b8d39b9,
    0x9837f050, 0x94f4efa8, 0x91c3d373, 0x8ea4398a, 0x8b95c1e3, 0x88980e80,
    0x85aac367, 0x82cd8698,
};

/*
 * HALFLIFE=32
 * Reaches the maximum value after completing 345 full periods.
 * Decays to zero after completing 2048 full periods.
 */
#define LOAD_AVG_PERIOD     32
#define LOAD_AVG_MAX        47742
#define LOAD_AVG_INIT       32000


#else
#error "Unsupported HALF_LIFE value."
#endif

/*
 * WARNING: DO NOT MODIFY !!!
 *
 * The above macros and variables are generated by
 * uas/performance/kernel_module/src/gen_inv.c
 */

#define ns_to_us(ns)    (ns >> 10)
#define us_to_ns(ns)    (ns << 10)

/*
 * Unsigned subtract and clamp on underflow.
 *
 * Explicitly do a load-store to ensure the intermediate value never hits
 * memory. This allows lockless observations without ever seeing the negative
 * values.
 */
#define sub_positive(_ptr, _val) do {               \
    typeof(_ptr) ptr = (_ptr);                      \
    typeof(*ptr) val = (_val);                      \
    typeof(*ptr) res, var = READ_ONCE(*ptr);        \
    res = var - val;                                \
    if (res > var)                                  \
        res = 0;                                    \
    WRITE_ONCE(*ptr, res);                          \
} while (0)

#ifdef TRANS_LOADING_DEBUG
/*
 * For debugging purposes. limits systrace logs to focus only on
 * specific tasks listed below, preventing excessive log output.
 */
static const char *key_tasks[] = {
    "surfaceflinger",
    "id.article.news",
    "load_test",
};
#define NUM_KEY_TASKS (sizeof(key_tasks) / sizeof(key_tasks[0]))

bool is_dbg_task(struct task_struct *tsk)
{
    bool ret = false;
    int i;

    for (i = 0; i < NUM_KEY_TASKS; i++) {
        if ((strcmp(tsk->comm, key_tasks[i]) == 0) &&
            (tsk->pid == tsk->tgid)) {
            ret = true;
            break;
        }
    }

    return ret;
}

#else

#define is_dbg_task(tsk) (false)

#endif

unsigned long trans_task_load(struct task_struct *p)
{
    struct trans_task_struct *tts = NULL;
    struct task_load *ld = NULL;
    unsigned long load_avg;

    tts = get_trans_task_struct(p);
    if (IS_ERR_OR_NULL(tts))
        return 0;

    load_avg = task_util_est(p);

    ld = &tts->ld;
    load_avg = max_t(u64, load_avg, max_t(u64, ld->load_avg, ld->load_est));

    trace_trans_task_load(p, load_avg);

    return load_avg;
}

unsigned long trans_task_load_uclamp(struct task_struct *p)
{
    unsigned long load_avg = trans_task_load(p);

    load_avg = clamp(load_avg,
                uclamp_eff_value(p, UCLAMP_MIN),
                uclamp_eff_value(p, UCLAMP_MAX));

    return load_avg;
}

/*
 * The margin used when comparing utilization with CPU capacity.
 *
 * (default: ~20%)
 */
#define fits_capacity(cap, max)    ((cap) * 1280 < (max) * 1024)

#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 12, 0)
static inline unsigned long capacity_orig_of(int cpu)
{
    return arch_scale_cpu_capacity(cpu);
}
#endif

bool task_fits_cpu(struct task_struct *p, int cpu)
{
    return fits_capacity(trans_task_load_uclamp(p), capacity_orig_of(cpu));
}

bool load_fits_cpu(unsigned long load_avg, int cpu)
{
    return fits_capacity(load_avg, capacity_orig_of(cpu));
}

bool need_boost(unsigned long load_avg)
{
    /*
     * If FEATURE_LOAD_TRACK is not enabled, all tasks are considered
     * high-load. In this case, all tasks will prioritize being
     * scheduled on high-performance CPUs.
     */
    if (!check_uas_feature(FEATURE_LOAD_TRACK))
        return true;

    return !load_fits_cpu(load_avg, 0);
}

bool is_highload(unsigned long load_avg)
{
    /*
     * If FEATURE_LOAD_TRACK is not enabled, all tasks are considered
     * high-load. In this case, all tasks will prioritize being
     * scheduled on high-performance CPUs.
     */
    if (!check_uas_feature(FEATURE_LOAD_TRACK))
        return true;

    return load_avg >= HIGH_LOAD_THRESHOLD;
}

bool task_is_on_runqueue(struct task_struct *tsk)
{
    if (!tsk)
        return false;

    if (task_state(tsk) != TASK_RUNNING)
        return false;

    return (tsk->on_rq == TASK_ON_RQ_QUEUED);
}

bool task_is_runnnig_on_cpu(struct task_struct *tsk)
{
    if (!tsk)
        return false;

    if (task_state(tsk) != TASK_RUNNING)
        return false;

    return ((tsk->on_rq == TASK_ON_RQ_QUEUED) &&
            smp_load_acquire(&tsk->on_cpu));
}

bool task_is_runnable_on_runqueue(struct task_struct *tsk)
{
    if (!tsk)
        return false;

    if (task_state(tsk) != TASK_RUNNING)
        return false;

    return ((tsk->on_rq == TASK_ON_RQ_QUEUED) &&
            !smp_load_acquire(&tsk->on_cpu));
}

/*
 * This task is executing the task_switch process
 */
bool task_is_switching(struct task_struct *tsk)
{
    int state;

    if (!tsk)
        return false;

    state = task_state(tsk);
    if (!(state & (TASK_INTERRUPTIBLE | TASK_UNINTERRUPTIBLE | TASK_DEAD)))
        return false;

    return true;
}

/*
 * This running task is being migrated to other cpus.
 */
bool task_is_migrating(struct task_struct *tsk)
{
    int state;

    if (!tsk)
        return false;

    if (tsk->on_rq != TASK_ON_RQ_MIGRATING)
        return false;

    state = task_state(tsk);
    if (state != TASK_RUNNING)
        return false;

    if (tsk->on_cpu == 0)
        return true;

    return false;
}

/*
 * waking a running task
 */
bool task_is_waking(struct task_struct *tsk)
{
    int state;

    if (!tsk)
        return false;

    state = task_state(tsk);
    if (state == TASK_WAKING && tsk->on_rq == 0)
        return true;

    return false;
}

/*
 * task is new forked
 */
bool task_is_new(struct task_struct *tsk)
{
    struct sched_info *si;
    int state;

    if (!tsk)
        return false;

    si = &tsk->sched_info;
    if (si->pcount)
        return false;

    state = task_state(tsk);
    if (state == TASK_RUNNING && tsk->on_cpu == 0 && tsk->on_rq == 0)
        return true;

    return false;
}

/*
 * return the total runtime of tsk since it was enqueued, including
 * the time spent in both running and runnable states.
 *
 * @tsk: The task whose runtime is to be retrieved.
 * @running: return the time the task spent in the running state.
 * @runnable: return the time the task spent in the runnable state.
 * @cpath: used to record the call path of this function for debugging purposes.
 */
void get_task_time(struct task_struct *tsk,
            u64 *running, u64 *runnable,
            enum call_path cpath)
{
    struct sched_info sched_info;
    struct trans_task_struct *tts = NULL;
    struct task_load *ld = NULL;
    struct rq *rq = NULL;
    u64 now, runnable_time = 0, running_time = 0;
    static u64 max_runnable_time = 0, max_running_time = 0;
    int scene = -1;

    tts = get_trans_task_struct(tsk);
    if (IS_ERR_OR_NULL(tts))
        return;
    ld = &tts->ld;

    /*
     * Idle tasks are not considered.
     */
    if (!tsk->pid)
        return;

    /*
     * Backup to prevent the sched_info of the task from
     * changing during the following calculations.
     */
    sched_info = tsk->sched_info;

    rq = cpu_rq(task_cpu(tsk));

    /*
     * get rq->lock without update
     */
    now = rq->clock;

    if (task_is_runnnig_on_cpu(tsk)) {
        /*
         * the task has completed at least one context switch.
         */
        runnable_time = sched_info.run_delay - ld->snap_run_delay;

        /*
         * The value of rq->lock may be less than tts->enqueue_time
         * because rq->lock is not the latest value.
         */
        if (ld->enqueue_time && ld->enqueue_time <= sched_info.last_arrival)
            running_time = now - ld->enqueue_time;
        else
            running_time = now - sched_info.last_arrival;

        if (running_time >= runnable_time)
            running_time = running_time - runnable_time;

        scene = 1;
    } else if (task_is_runnable_on_runqueue(tsk)) {
        if (ld->snap_pcount == sched_info.pcount) {
            /*
             * the task has not been executed since it was enqueued.
             */
            runnable_time = now - ld->enqueue_time;
            running_time = 0;

            scene = 2;
        } else if (sched_info.last_queued) {
            /*
             * the task has completed one or more context switches.
             */
            runnable_time = (now - sched_info.last_queued) +
                    (sched_info.run_delay - ld->snap_run_delay);

            /*
             * The value of rq->lock may be less than tts->enqueue_time
             * because rq->lock is not the latest value.
             */
            running_time = now - ld->enqueue_time;
            if (running_time >= runnable_time)
                running_time = running_time - runnable_time;

            scene = 3;
        } else {
            scene = 4;
            running_time = runnable_time = 0;
#ifdef TRANS_LOADING_DEBUG
            trace_printk("LOADING: unhandled scene%d !!! tsk=%s$%d\n",
                    scene, tsk->comm, tsk->pid);
#endif
        }
    } else if (task_is_switching(tsk)) {
        /*
         * the task is switching out
         */
        runnable_time = sched_info.run_delay - ld->snap_run_delay;

        if (ld->enqueue_time && ld->snap_pcount <= sched_info.pcount)
            running_time = now - ld->enqueue_time;
        else
            running_time = now - sched_info.last_arrival;

        if (running_time >= runnable_time)
            running_time = running_time - runnable_time;

        scene = 5;
    } else if (task_is_migrating(tsk)) {
        /*
         * this running task is being migrated to other cpus.
         */
        runnable_time = sched_info.run_delay - ld->snap_run_delay;

        if (ld->enqueue_time)
            running_time = now - ld->enqueue_time;
        else
            running_time = now - sched_info.last_arrival;

        if (running_time >= runnable_time)
            running_time = running_time - runnable_time;

        scene = 6;
    } else if (task_is_waking(tsk)) {
        /*
         * this task is being woken up.
         */
        runnable_time = 0;
        if (ld->enqueue_time)
            running_time = now - ld->enqueue_time;
        else
            running_time = 0;

        scene = 7;
    } else if (task_is_new(tsk)) {
        /*
         * this is a newly created task
         */
        scene = 8;
        running_time = runnable_time = 0;
    } else {
        /*
         * This is a scenario that should never occur,
         * a warning message will be printed directly.
         */
        scene = 9;
        running_time = runnable_time = 0;
#ifdef TRANS_LOADING_DEBUG
        trace_printk("LOADING: unhandled scene%d !!! tsk=%s$%d\n",
                scene, tsk->comm, tsk->pid);
#endif
    }

    if (running)
        *running = running_time;
    if (runnable)
        *runnable = runnable_time;

    /*
     * for debug purposes, used to record the maximum values
     * of the running and runnable states for all tasks in
     * the system.
     */
    max_runnable_time = max_t(u64, max_runnable_time, runnable_time);
    max_running_time = max_t(u64, max_running_time, running_time);

    trace_get_task_time(cpath, scene, tsk, &sched_info,
            running_time, runnable_time,
            max_running_time, max_runnable_time);

    if (is_dbg_task(tsk)) {
        trace_running_time(task_pid_nr(tsk), running_time);
        trace_runnable_time(task_pid_nr(tsk), runnable_time);
    }

    return;
}

u64 get_running_time(struct task_struct *tsk)
{
    u64 running_time = 0;

    get_task_time(tsk, &running_time, NULL, -1);
    return running_time;
}

u64 get_runnable_time(struct task_struct *tsk)
{
    u64 runnable_time = 0;

    get_task_time(tsk, NULL, &runnable_time, -1);
    return runnable_time;
}

/*
 * TODO
 * This variable should be passed from user space instead of being hardcoded.
 */
int frame_rate = 90;

/*
 * Calculate the weight corresponding to a given time duration in nanoseconds.
 *
 * The refresh period is defined as:
 *
 *                    1 * 1000 * 1000 * 1000
 * refresh_period = --------------------------- ns
 *                           frame_rate
 *
 * Assuming a task runs continuously for 2/3 of one refresh period, the
 * weight is defined as 1024. For a task running for `t` nanoseconds,
 * the weight is calculated as:
 *
 *                  1024 * t
 * weight = --------------------------
 *            refresh_period * (2/3)
 *
 * Substituting the refresh_period formula:
 *
 *            3 * 1024 * t * frame_rate
 * weight = ----------------------------
 *             2 * 1000 * 1000 * 1000
 *
 * To optimize this calculation, it can be rewritten as:
 *
 *             3 * 1024 * frame_rate * 2^32
 * weight = --------------------------------- * t
 *             2 * 1000 * 1000 * 1000 * 2^32
 *
 *             3 * 1024 * frame_rate * 2^32
 *         = --------------------------------- * t >> 32
 *                2 * 1000 * 1000 * 1000
 *
 *         = (TIME2WEIGHT_FPS * t) >> 32
 *
 * The macro TIME2WEIGHT_FPS is precomputed for different frame rates:
 *
 * TIME2WEIGHT_60FPS  = 0x00060a30
 * TIME2WEIGHT_90FPS  = 0x00090f48
 * TIME2WEIGHT_120FPS = 0x000c1460
 *
 */

#define TIME2WEIGHT_60FPS   0x00060a30
#define TIME2WEIGHT_90FPS   0x00090f48
#define TIME2WEIGHT_120FPS  0x000c1460

u64 time_to_weight(u64 time_ns)
{
    u64 coef;
    u64 weight;

    switch (frame_rate) {
        case 60:
            coef = TIME2WEIGHT_60FPS;
            break;
        case 90:
            coef = TIME2WEIGHT_90FPS;
            break;
        case 120:
            coef = TIME2WEIGHT_120FPS;
            break;
        default:
            WARN(1, "Unsupported frame rate: %d, switching to default 90FPS\n",
                    frame_rate);
            coef = TIME2WEIGHT_90FPS;
            break;
    }

    weight = (coef * time_ns) >> 32;
    return min_t(u64, 1024, weight);
}

/*
 * Normalize the task's load to a scale of 1024.
 *
 * This function calculates a normalized load value for a task by considering
 * both historical contributions and the current time segment's progress. The
 * normalization ensures that the load value is consistent and comparable
 * across tasks.
 *
 * Design rationale:
 *
 * - The `divider` is calculated as
 *   `LOAD_AVG_MAX - LOADTRACK_PERIOD_US + ns_to_us(ld->period_contrib)`.
 *   This represents the maximum possible load contribution at the current
 *   moment, taking into account both historical contributions and the
 *   progress within the current time segment.
 *
 * - `LOAD_AVG_MAX - LOADTRACK_PERIOD_US`:
 *   - This term represents the theoretical maximum load contribution from
 *     all completed time segments in the past, excluding the current segment.
 *   - By subtracting `LOADTRACK_PERIOD_US`, the design ensures that the
 *     current segment's contribution is excluded from historical
 *     contributions, providing a clean baseline for further adjustments.
 *
 * - `ns_to_us(ld->period_contrib)`:
 *   - This term adds the task's runtime contribution within the current time
 *     segment, measured in microseconds.
 *   - Including this value ensures that the partial contribution from the
 *     current segment is accounted for, preventing underestimation of the
 *     task's load when the segment is incomplete.
 *
 * - The final `divider` dynamically reflects the task's load potential at
 *   the current moment, balancing historical contributions and current
 *   progress.
 * - The normalized load is then scaled to a range of 0–1024, making it
 *   easier to compare task loads and integrate them into scheduling decisions.
 *
 * This approach prevents undesirable oscillations in load calculations and
 * ensures a smooth transition between time segments, maintaining accurate
 * and stable load tracking for tasks.
 */
u64 trans_scale_load(struct task_load *ld)
{
    u64 divider;
    u64 load_avg;

    divider = LOAD_AVG_MAX - LOADTRACK_PERIOD_US + ns_to_us(ld->period_contrib);
    load_avg = div_u64(ld->load_sum * 1024, divider);

    return load_avg;
}

u64 time_scale(u64 delta, int cpu)
{
    /*
     * When a rq runs at a lower compute capacity, it will need
     * more time to do the same amount of work than at max
     * capacity. In order to be invariant, we scale the delta to
     * reflect how much work has been really done.
     * Running longer results in stealing idle time that will
     * disturb the load signal compared to max capacity. This
     * stolen idle time will be automatically reflected when the
     * rq will be idle and the clock will be synced with
     * rq_clock_task.
     */

    /*
     * Scale the elapsed time to reflect the real amount of
     * computation
     */
    delta = cap_scale(delta, arch_scale_cpu_capacity(cpu));
    delta = cap_scale(delta, arch_scale_freq_capacity(cpu));

    return delta;
}

/*
 * Approximate:
 *   val * y^n,
 *
 * where y^128 ~= 0.5 (~1 scheduling period)
 * y ~= 0.99459942348363317155
 *
 */
static u64 decay_load(u64 val, u64 n)
{
    unsigned int local_n;

    if (unlikely(n > LOAD_AVG_PERIOD * 63))
        return 0;

    /* after bounds checking we can collapse to 32-bit */
    local_n = n;

    /*
     * As y^PERIOD = 1/2, we can combine
     *    y^n = 1/2^(n/PERIOD) * y^(n%PERIOD)
     * With a look-up table which covers y^n (n<PERIOD)
     *
     * To achieve constant time decay_load.
     */
    if (unlikely(local_n >= LOAD_AVG_PERIOD)) {
        val >>= local_n / LOAD_AVG_PERIOD;
        local_n %= LOAD_AVG_PERIOD;
    }

    val = mul_u64_u32_shr(val, load_yN_inv[local_n], 32);
    return val;
}

/*
 * Update the load information of a specified task.
 *
 * @tsk: The task whose load information is to be updated.
 * @ld: A structure that stores load-related information for the task.
 * @now: The current timestamp, typically representing rq->clock of the CPU.
 * @contrib: The time duration (in nanoseconds) during which the task has
 *           been in the running or runnable state since the last update.
 *
 * This function calculates and updates the task's load contribution to the
 * system based on its runtime and runnable time since the last update.
 *
 * Accumulate the three separate parts of the sum; d1 the remainder
 * of the last (incomplete) period, d2 the span of full periods and d3
 * the remainder of the (incomplete) current period.
 *
 *           d1          d2           d3
 *           ^           ^            ^
 *           |           |            |
 *         |<->|<----------------->|<--->|
 * ... |---x---|------| ... |------|-----x (now)
 *
 *
 * u' = u y^p + d1 y^p + T y^(p-1) + T y^(p-2) + ... + T y^1 + d3 y^0
 *
 *                          p-1
 *    = u y^p + d1 y^p + T \Sum y^n + d3 y^0
 *                          n=1
 *
 *                            inf        inf
 *    = u y^p + d1 y^p +  T (\Sum y^n - \Sum y^n - y^0) + d3 y^0
 *                            n=0        n=p
 *
 *                            inf            inf
 *    = u y^p + d1 y^p +  T (\Sum y^n - y^p \Sum y^n - y^0) + d3 y^0
 *                            n=0            n=0
 *
 *                           inf                  inf
 *    = u y^p + d1 y^p +  T \Sum y^n - (y^p) * T \Sum y^n - T + d3 y^0
 *                           n=0                  n=0
 *
 *
 *    = u y^p + d1 y^p +  LOAD_AVG_MAX - LOAD_AVG_MAX y^p - T + d3 y^0
 *
 *
 *
 *    = u y^p +                                             (Step 1)
 *          d1 y^p +                                        (Step 2)
 *          LOAD_AVG_MAX - LOAD_AVG_MAX y^p - T +           (Step 3)
 *          d3 y^0                                          (Step 4)
 *
 */
void accumulate_loading(struct task_struct *tsk,
            struct task_load *ld, u64 now, u64 contrib)
{
    struct load_env env;
    u64 delta = 0;
    u64 c = 0;

    env.raw_contrib = contrib;
    env.tsk = tsk;
    env.ld = ld;
    env.now = now;

    /*
     * Convert the unit from ns to us
     *
     * If the converted value of env.contrib is 0, it indicates that
     * env.contrib might be less than 1 microsecond. To prevent this
     * duration from being discarded, the function should return early
     * when env.contrib is less than 1 microsecond, skipping the
     * subsequent update logic.
     */
    contrib = time_scale(contrib, task_cpu(tsk));
    env.scale_contrib = ns_to_us(contrib);
    if (contrib && !env.scale_contrib)
        return;

    /*
     * If the time since the last update is less than one period,
     * the following load value is directly returned.
     */
    env.load_sum = ld->load_sum + env.scale_contrib;
    delta = now - ld->last_update;
    env.raw_delta = delta;
    delta = time_scale(delta, task_cpu(tsk));
    env.scale_delta = delta;

    ld->last_update = now;

    delta += ld->period_contrib;
    env.delta_contrib = delta;
    delta = ns_to_us(delta);

    /*
     * Calculate how many complete periods have passed since the last update.
     *
     * A period is 1024us (~1ms).
     */
    env.periods = delta / LOADTRACK_PERIOD_US;

    /*
     * Decay the historical load if several complete periods have
     * passed since the last update.
     */
    if (env.periods) {
        /*
         * Step1:
         * Decay the historical load.
         *
         * u y^p
         */
        env.u = decay_load(ld->load_sum, env.periods);

        delta %= LOADTRACK_PERIOD_US;
        if (contrib) {
            /*
             * Step 2:
             * Decay the load of d1 (the remainder of the last incomplete period).
             *
             * c1 = d1 * y^p
             */
            env.d1 = LOADTRACK_PERIOD_US - ns_to_us(ld->period_contrib);
            env.c1 = decay_load(env.d1, env.periods);

            /*
             * Step3:
             * Calculate the load contribution of d2 (the span of full periods).
             *
             * c2 = LOAD_AVG_MAX - LOAD_AVG_MAX y^p - T
             */
            env.c2 = LOAD_AVG_MAX
                        - decay_load(LOAD_AVG_MAX, env.periods)
                        - LOADTRACK_PERIOD_US;

            /*
             * Step 4:
             * Calculate the load contribution of d3 (the remainder of the
             * incomplete current period).
             *
             * c3 = d3 * y^0
             */
            env.c3 = env.d3 = delta;

            /*
             * Add up the contributions to obtain the load generated during
             * this runtime.
             */
            c = env.c1 + env.c2 + env.c3;
        }

        /*
         * Add the historical load to obtain the total load generated by
         *  this task over its entire lifecycle.
         */
        env.load_sum = env.u + c;
    }

    env.delta = delta;
    trace_accumulate_load(&env);

    /*
     * Record the remaining portion of the current period.
     */
    ld->period_contrib = us_to_ns(delta);

#ifndef TRANS_LOADING_DEBUG
    /*
     * If the TRANS_LOADING_DEBUG macro is not enabled, the real
     * env.load_sum value is used to expose issues.
     */
    env.load_sum = min_t(u64, env.load_sum, LOAD_AVG_MAX);
#endif

    /*
     * Update the task load and normalize it to a scale of 1024.
     */
    ld->load_sum = env.load_sum;
    if (env.periods)
        ld->load_avg = trans_scale_load(ld);

    /*
     * Return the total load generated by the task over its entire lifecycle.
     */
    return;
}

#define LOAD_EST_MARGIN            (1024 / 100)

/*
 * Check if a (signed) value is within a specified (unsigned) margin,
 * based on the observation that:
 *
 *     abs(x) < y := (unsigned)(x + y - 1) < (2 * y - 1)
 *
 * NOTE: this only works when value + margin < INT_MAX.
 */
static inline bool within_margin(int value, int margin)
{
    return ((unsigned int)(value + margin - 1) < (2 * margin - 1));
}

#ifdef ENABLE_PELT_COMPAT
#define LOAD_EST_WEIGHT_SHIFT        (2)
#else

/*
 * We are more interested in sudden changes in workload.
 */
#define LOAD_EST_WEIGHT_SHIFT        (1)
#endif

void update_load_est(struct task_struct *tsk)
{
    struct trans_task_struct *tts = NULL;
    struct task_load *ld = NULL;
    struct task_load snap_ld;
    long last_avg_diff, last_est_diff;        /* signed */
    u64 load_avg, load_est;

    tts = get_trans_task_struct(tsk);
    if (IS_ERR_OR_NULL(tts))
        return;

    snap_ld = tts->ld;
    ld = &tts->ld;

    load_est = ld->load_est;                /* load_est(t-1) */
    load_avg = ld->load_avg;                /* load_avg(t)   */

    /*
     * Implement faster ramp-up EWMA on utilization increases
     *
     * When a task suddenly changes its bandwidth requirements from
     * small to big, the EWMA will need to collect multiple samples
     * before converging up to track the new big utilization.
     *
     * This slow convergence towards bigger utilization values is
     * not aligned to the default scheduler behavior, which is to
     * optimize for performance.
     *
     * To let load_est do a better job in the scenario depicted
     * above, change its definition by making load_est directly
     * follow upward motion and only decay the load_est on
     * downward.
     */
    if (load_est < load_avg) {
        ld->load_est = load_avg;
        goto out;
    }

    /*
     * Skip update of task's estimated utilization when its members are
     * already ~1% close to its last activation value.
     */
    last_avg_diff = ld->last_load_avg - load_avg;
    if (within_margin(last_avg_diff, LOAD_EST_MARGIN)) {
        goto out;
    }
    ld->last_load_avg = load_avg;

    /*
     * last_est_diff = load_avg(t) - load_est(t-1)
     */
    last_est_diff = load_avg - load_est;

    /*
     * Update Task's estimated utilization
     *
     * When a task completes an execution, its estimated workload for
     * the next execution can be determined by calculating the Exponential
     * Weighted Moving Average (EWMA) of the current execution time and
     * historical execution times.
     *
     * The formula for load_est(t) is as follows:
     *
     * load_est(t) = w * load_avg(t) + (1-w) * load_est(t-1)
     *
     *             = w * load_avg(t) + load_est(t-1) - w * load_est(t-1)
     *
     *             = w * (load_avg(t) - load_est(t-1)) + load_est(t-1)
     *
     *             = w * last_est_diff + load_est(t-1)
     *
     *             = w * (last_est_diff + load_est(t-1)/w)
     *
     *
     * Where:
     *
     *      last_est_diff = load_avg(t) - load_est(t-1)
     *
     *                     1                     1
     *      w = ------------------------------ = ---
     *           1 << LOAD_EST_WEIGHT_SHIFT      4
     *
     *
     * Thus:
     *
     * load_est(t) = w * (last_est_diff + load_est(t-1)/w)
     *
     *                1
     *             = --- * (last_est_diff + load_est(t-1) * 4)
     *                4
     *
     *             = (last_est_diff +                           (step2)
     *               load_est(t-1) << LOAD_EST_WEIGHT_SHIFT     (step1)
     *               ) >> LOAD_EST_WEIGHT_SHIFT                 (step3)
     *
     */
    load_est <<=  LOAD_EST_WEIGHT_SHIFT;                     /* (step1) */
    load_est += last_est_diff;                               /* (step2) */
    load_est >>= LOAD_EST_WEIGHT_SHIFT;                      /* (step3) */

    /*
     * update
     */
    ld->load_est = load_est;

out:
    trace_update_load_est(tsk, &snap_ld, ld);
    if (is_dbg_task(tsk)) {
        trace_trans_load_est(task_pid_nr(tsk), ld->load_est);
        trace_util_est(task_pid_nr(tsk), _task_util_est(tsk));
    }
}

/*
 * Update the load information of a task.
 *
 * @tsk: The task whose load information is to be updated.
 * @cpath: Indicates the callpath of this function, primarily used for debug.
 *
 * The load information of a task is updated at the following points:
 * a) update_curr -> trace_sched_stat_runtime
 * b) scheduler_tick -> trace_android_vh_scheduler_tick
 * c) enqueue_task -> trace_android_rvh_enqueue_task -> trans_task_loading_enqueue
 * d) dequeue_task -> trace_android_rvh_dequeue_task -> trans_task_loading_dequeue
 */
void update_task_loading(struct task_struct *tsk, enum call_path cpath)
{
    struct trans_task_struct *tts = NULL;
    struct task_load snap_load;
    struct task_load *ld = NULL;
    struct rq *rq = NULL;
    u64 running_time = 0, runnable_time = 0;
    u64 enqueue_time, last_running_time = 0;
    u64 now = 0, delta = 0;      /* in us */
    u64 load_contrib = 0;
    u64 periods = 0;
    unsigned long irqflag;
    u64 sc[2];

    if (!check_uas_feature(FEATURE_LOAD_TRACK))
        return;

    /*
     * Newly created task runs on the CPU for the first time,
     * its sched_info has not been updated yet.
     */
    if (!tsk->sched_info.pcount)
        return;

    tts = get_trans_task_struct(tsk);
    if (IS_ERR_OR_NULL(tts))
        return;

    ld = &tts->ld;
    snap_load = tts->ld;

    /*
     * get rq->lock without update
     */
    rq = cpu_rq(task_cpu(tsk));
    now = rq->clock;

    sc[0] = sched_clock();
    spin_lock_irqsave(&ld->lock, irqflag);

    /*
     * Record the enqueue time when the task is first enqueued.
     */
    if (cpath == CPATH_ENQUEUE && task_state(tsk) == TASK_WAKING) {
        enqueue_time = now;

        if (task_on_rq_migrating(tsk))
            enqueue_time -= ld->last_running_time;

        record_enqueue_time(tsk, enqueue_time);
    }

    /*
     * The load tracking module has just started working and some related
     * variables have not been initialized yet
     */
    if (!ld->snap_pcount)
        goto out;

    /*
     * Skip if this is the first time updating the task's load information,
     * as it may cause an excessively large delta value in the subsequent
     * calculation.
     */
    if (!ld->last_update) {
        ld->last_update = now;
        goto out;
    }

    /*
     * Prevent time overflow or rollback
     */
    delta = now - ld->last_update;
    if ((s64)delta < 0)
        goto out;

    /*
     * Convert the time unit from ns to us.
     *
     * Skip the update if the interval between two updates is less than 10us.
     */
    if (ns_to_us(delta) < UPDATE_GRAN_US)
        goto out;

    last_running_time = ld->last_running_time;
    get_task_time(tsk, &running_time, &runnable_time, cpath);
    ld->last_running_time = running_time + runnable_time;
    load_contrib = ld->last_running_time;

    if (!ld->last_running_time)
        load_contrib = 0;
    else {
        sub_positive(&load_contrib, last_running_time);
        /*
         * If load_contrib equals 0, a decay operation will be executed
         * in the subsequent accumulate_loading, which is not the
         * desired outcome.
         */
        if (!load_contrib)
            load_contrib = 1;
    }

    /*
     * Update the load information of the task.
     */
    accumulate_loading(tsk, ld, now, load_contrib);

    /*
     * The estimated workload is calculated when the task finishes execution.
     */
    if (cpath == CPATH_DEQUEUE && task_state(tsk) != TASK_RUNNING) {
        update_load_est(tsk);
    }

out:
    trace_update_task_load(cpath, tsk, &snap_load, now, delta, periods);
    if (is_dbg_task(tsk)) {
        trace_last_running(task_pid_nr(tsk), ld->last_running_time);
        trace_contrib(task_pid_nr(tsk), load_contrib);

        trace_trans_load_sum(task_pid_nr(tsk), ld->load_sum);
        trace_trans_load_avg(task_pid_nr(tsk), ld->load_avg);

        trace_runnable_avg(task_pid_nr(tsk), task_runnable_avg(tsk));
        trace_util_avg(task_pid_nr(tsk), task_util(tsk));
    }

    /*
     * Clear the enqueue time when the task is about to leave the runqueue.
     */
    if (cpath == CPATH_DEQUEUE && task_state(tsk) != TASK_RUNNING) {
        record_enqueue_time(tsk, 0);
    }

    spin_unlock_irqrestore(&ld->lock, irqflag);

    sc[1] = sched_clock();
    trace_update_task_load_consume(tsk, sc[1]-sc[0]);
}

void record_enqueue_time(struct task_struct *tsk, u64 enqueue_time)
{
    struct trans_task_struct *tts = NULL;
    struct task_load *ld = NULL;

    if (!tsk)
        return;

    tts = get_trans_task_struct(tsk);
    if (IS_ERR_OR_NULL(tts))
        return;
    ld = &tts->ld;

    lockdep_assert_held(&ld->lock);

    ld->enqueue_time = enqueue_time;
    ld->snap_pcount = tsk->sched_info.pcount;
    ld->snap_run_delay = tsk->sched_info.run_delay;
}

void trans_task_loading_enqueue(struct rq *rq,
            struct task_struct *tsk, int flags)
{
    update_task_loading(tsk, CPATH_ENQUEUE);
}

void trans_task_loading_dequeue(struct rq *rq,
            struct task_struct *tsk, int flags)
{
    update_task_loading(tsk, CPATH_DEQUEUE);
}

#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 12, 0)
static void trans_sched_stat_runtime(void *unused,
            struct task_struct *tsk, u64 runtime)
#else
static void trans_sched_stat_runtime(void *unused,
            struct task_struct *tsk, u64 runtime, u64 vruntime)
#endif
{
    update_task_loading(tsk, CPATH_UPDATE);
}

void init_task_load(struct task_load *ld)
{
    memset(ld, 0, sizeof(struct task_load));

    /*
     * Setting the initial load for a newly created task is challenging
     * because we cannot determine in advance whether the task is
     * CPU-bound or I/O-bound. Assigning an overly high initial load to
     * an I/O-bound task will result in a prolonged decay period before
     * its load reaches the actual value. Similarly, assigning a low
     * initial load to a CPU-bound task may cause it to be placed on a
     * little core, leading to insufficient CPU resources and prolonged
     * execution times.
     *
     * To address this, we must predict the load of new tasks. Adopting
     * a conservative approach, we assume that the new task is CPU-bound
     * and set its initial load to HIGH_LOAD_THRESHOLD. This strategy
     * ensures that CPU-bound tasks can immediately access
     * high-performance CPUs while allowing I/O-bound tasks to quickly
     * decay their load to the correct value, avoiding excessive use of
     * high-performance resources.
     */
    ld->load_est = 1024;

    spin_lock_init(&ld->lock);
}

int register_trans_loading_hook(void)
{
    int ret = 0;

    /*
     * rt, deadline, cfs
     */
    ret = register_trace_sched_stat_runtime(trans_sched_stat_runtime, NULL);
    if (ret != 0) {
        trans_warn("trans_sched_stat_runtime failed! ret=%d\n", ret);
    }

    return ret;
}

