ccflags-y += \
	-I$(srctree)/ \
	-I$(srctree)/include/ \
	-I$(srctree)/drivers/misc/mediatek/sched/trans_sched/ \
	-I$(srctree)/drivers/unisoc_platform/sched/trans_sched/ \
	-I$(srctree)/../vendor/transsion/spd/uas/performance/kernel_module/include/ \
	-I$(srctree)/../vendor/transsion/spd/uas/performance/kernel_module/src/ \
	-I$(srctree)/$(src)/include/ \
	-I$(srctree)/$(src)/src/ \
	-I$(srctree)/../../../vendor/transsion/spd/uas/performance/kernel_module/include/

ifneq ("$(wildcard $(srctree)/../kernel_device_modules-6.1)","")
    ccflags-y += -I$(srctree)/../kernel_device_modules-6.1/drivers/misc/mediatek/sched/trans_sched
else ifneq ("$(wildcard $(srctree)/../kernel_device_modules-6.6)","")
    ccflags-y += -I$(srctree)/../kernel_device_modules-6.6/drivers/misc/mediatek/sched/trans_sched
endif

ifneq ($(CONFIG_TRANSSION_BLK_UAS),)
ifeq ($(CONFIG_TRANSSION_BLK_UAS),$(filter $(CONFIG_TRANSSION_BLK_UAS),y m))
ccflags-y += \
	-I$(srctree)/drivers/scsi/ufs/ \
	-I$(srctree)/drivers/scsi/ufs/tran_ufs/ \
	-I$(srctree)/drivers/scsi/ufs/vendor/ \
	-I$(srctree)/drivers/misc/mediatek/aee/mrdump/ \
	-I$(srctree)/../vendor/transsion/std/vendor_vnd/low_latency_sched/include/
ifneq ("$(wildcard $(srctree)/../kernel_device_modules-6.1)","")
	ccflags-y += -I$(srctree)/../kernel_device_modules-6.1/fs/atomic_storage/tran_ufs/ \
		     -I$(srctree)/../kernel_device_modules-6.1/fs/atomic_storage/tran_block/low_latency_sched/include/
else ifneq ("$(wildcard $(srctree)/../kernel_device_modules-6.6)","")
	ccflags-y += -I$(srctree)/../kernel_device_modules-6.6/fs/atomic_storage/tran_ufs/ \
		     -I$(srctree)/../kernel_device_modules-6.6/fs/atomic_storage/tran_block/low_latency_sched/include/
endif
endif
endif

obj-$(CONFIG_TRANS_SCHED_FEATURE) += trans_sched.o

trans_sched-y += src/sched_main.o
trans_sched-y += src/trans_pcb.o
trans_sched-y += src/sched_common.o
trans_sched-y += src/trans_fair.o
trans_sched-y += src/trans_proc.o
trans_sched-y += src/trans_sched_info.o
trans_sched-y += src/trans_binder.o
trans_sched-y += src/trans_mutex.o
trans_sched-y += src/trans_rwsem.o
trans_sched-y += src/trans_target.o
trans_sched-y += src/trans_balance.o
trans_sched-y += src/trans_locking.o
trans_sched-y += src/trans_loading.o
trans_sched-y += src/trans_trace.o
trans_sched-y += src/trans_futex.o
trans_sched-y += src/trans_workqueue.o
trans_sched-y += src/trans_xmu.o
